version: '3.3'
services:
  kaggle-template:
    build: ./Dockerfile
    container_name: kaggle-template
    hostname: kaggle-template
    shm_size: '28gb'
    deploy:
      resources:
        reservations:
          devices:
           - driver: nvidia
             capabilities: ["gpu"]
    volumes:
      - ./:/workspace:cached
      - ./kaggle:/kaggle:cached
      - ${DATASTORAGE_PATH}:/data_storage:cached
      - ${MLFLOW_STORAGE_PATH}:/content/drive/MyDrive/Colab Notebooks/mlruns
      - ${MLFLOW_STORAGE_PATH}:/workspace/log/google_drive/mlruns
    environment:
      TZ: Asia/Tokyo
      KAGGLE_USERNAME: ${KAGGLE_USERNAME}
      KAGGLE_KEY: ${KAGGLE_KEY}
      MLFLOW_TRACKING_URI: /workspace/log/local/mlruns
      DISPLAY: host.docker.internal:0.0
      PULSE_SERVER: tcp:host.docker.internal
    tty: true
